# Generated by Django 3.2.7 on 2021-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiclink',
            name='token',
        ),
        migrations.AddField(
            model_name='magiclink',
            name='code',
            field=models.CharField(default='12345', max_length=6),
            preserve_default=False,
        ),
    ]
