# Generated by Django 3.2.7 on 2021-09-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0002_alter_customuser_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
